### ISSUE TITLE
Bug In Reset Manual Override in 1.1.0-b3

### ISSUE THREAD

**Issue by Colorado4Wheeler** [basbruss/adaptive-cover#103]
## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1414
Downloaded Repositories | 41

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 28, 2024 at 5:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | us-east-1-2.ui.nabu.casa
certificate_status | ready
instance_id | e4c3b0fc2d6345dd91513a760ef8ba51
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 196.2 GB
disk_used | 120.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Terminal & SSH (9.13.0), Mosquitto broker (6.4.0), Samba Backup (5.2.0), HA Command Center (0.6.0), Z-Wave JS UI (3.4.2), Check Home Assistant configuration (3.11.0), Studio Code Server (5.15.0), NGINX Home Assistant SSL proxy (3.9.0), MariaDB (2.6.1), phpMyAdmin (0.9.1), InfluxDB (5.0.0), RTSP Simple Server Add-on (v0.17.6), ESPHome (2024.3.2), eufy-security-ws (1.8.0-2), Node-RED (17.0.11)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 26
views | 64
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 2, 2024 at 3:46 PM
-- | --
current_recorder_run | April 13, 2024 at 8:47 AM
estimated_db_size | 4252.48 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

In the new feature I have the Toggle Control off for a particular shade, the expectation is that any manual override doesn't cause the automation to trigger if it's disabled in the first place.  This might be how it is intended to work, but intuitively I would expect that manual override does nothing when it expires if the automation is disabled in the first place.

On a side note: the manual override is a fantastic feature, these changes are really providing a lot of value to the extension and I love the direction it's going!  With each release this is becoming more and more central to my climate automation systems in Home Assistant.  Thank you for writing this!

### Reproduction steps

1. Toggle off the automation on a device
2. Set the curtain
3. Click Reset Manual Override
4. The cover will execute the automation regardless
5. However, if you wait for manual override to expire naturally, then it works properly and doesn't attempt to run automation
...

### Diagnostics dump

N/A

**Comment by basbruss** [comment]
Thanks for testing out this beta, this input helps enormously with determining the right implications of the new features. So if the `toggle control` switch is `off` you would expect that nothing from this integration can adjust the position of the cover(s)? But only erases the mark of `manual controlled` of the blind. (could be useful in case you changed the position manual, then toggle the switch to off and switch it back to on before the duration is ended). In that case it will be again autocontrolled after the switch is returned to on while you clicked the reset button in the off state.

**Comment by Colorado4Wheeler** [comment]
Yes, pretty much how I figured it was to work.  Like I had mentioned, it doesn't happen when the manual operation times out naturally, only if you click the button - and nobody is likely to click the button otherwise.  I can see why it works how it does now too, lets you just force and adjustment even if the system is off - maybe for a bit more manual control but with the smarts of the sensors you create.  It could go either way honestly!

**Comment by basbruss** [comment]
Closed as fixed by #104
