### ISSUE TITLE
Modify Automation Configuration doesn't save

### ISSUE THREAD

**Issue by The-Moops** [basbruss/adaptive-cover#106]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.5.0-25-generic
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 15, 2024 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-6.ui.nabu.casa
certificate_status | ready
instance_id | 0319c6ee631e4b35a0514cd43d18ff3f
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 3
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 5, 2024 at 11:58 PM
-- | --
current_recorder_run | April 15, 2024 at 10:43 AM
estimated_db_size | 67.26 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Any changes to the Automation Configuration menu don't save, both when initially setting up the integration and when editing an existing one.

### Reproduction steps

1. In the Integration page click CONFIGURE for any entry
2. Click Modify Automation Configuration
3. Change any setting 
4. Submit
5. Re-enter menu to see if changes persist
...

**Comment by basbruss** [comment]
Thanks, everything is saved in the backend, but not displayed after reopening the menu.
This PR #94 already covered the fix
