### ISSUE TITLE
Climate settings unable to be reconfigured

### ISSUE THREAD

**Issue by mguyard** [basbruss/adaptive-cover#109]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.10.0-28-amd64
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1403
Downloaded Repositories | 26

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 19 juin 2024 à 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-18.ui.nabu.casa
certificate_status | ready
instance_id | 381927b4921b47a797e587e8790e1775
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.5.1
docker_version | 26.0.0
disk_total | 194.4 GB
disk_used | 20.8 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Samba Backup (5.2.0), AppDaemon (0.16.4), Mosquitto broker (6.4.0), Zigbee2MQTT (1.36.1-1), Z-Wave JS UI (3.4.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 16 février 2024 à 21:39
-- | --
current_recorder_run | 16 avril 2024 à 12:21
estimated_db_size | 1671.70 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When i want to reconfigure a existing cover, i'm unable to update Climate settings
![CleanShot 2024-04-16 at 13 51 09](https://github.com/basbruss/adaptive-cover/assets/5262395/4e218e4c-b2ee-49b5-b1f9-4ed5ed5504fa)

### Reproduction steps

1. Create a cover
2. Try to reconfigure the previous created as show in description

**Comment by basbruss** [comment]
It’s part of the `fine tune blind settings` menu 😉

**Comment by mguyard** [comment]
this is what i have and i don't have configuration for temperature threshold and sensors
![image](https://github.com/basbruss/adaptive-cover/assets/5262395/2cae55ae-82c2-4948-a87c-d4fb95d09779)

**Comment by mguyard** [comment]
Ok my bad, i've find now that's in a second step of fine tune blind settings.
Thank you

**Comment by basbruss** [comment]
Just click on valider, it will be in the next step
