### ISSUE TITLE
Add lux/irradiation/temperature tests for Calculated position

### ISSUE THREAD

**Issue by mguyard** [basbruss/adaptive-cover#112]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Today is a cloudy day at home, but integration close to 6% my covers where sun is in front. But in fact, we have no sun really to generate glare.

### Describe the solution you'd like

Ability to add condition on lux for normal mode
![CleanShot 2024-04-17 at 15 53 04](https://github.com/basbruss/adaptive-cover/assets/5262395/df82b4ef-7336-43ed-b6b4-2d7c6487865d)

I also think a external temperature trigger can be also useful to allow to manage energy saving also in normal mode or climate mode with presence. For example, if the day is hot, in addition to manage glare, we will be able to block room temperature increasing.
Something like this (addition is in red) :
![image](https://github.com/basbruss/adaptive-cover/assets/5262395/422079e1-bc5a-4bef-8ec5-cc8d7ba1a69a)

When we need to do ecologic effort to save our planet, i think this can be useful for many people.

### Describe alternatives you've considered

As alternative i known that we can disable disable control on some context and manage position with an automation but this will complex all the cover management.

### Additional context

N/A

**Comment by basbruss** [comment]
Normal mode is a mode that calculates the position only based on the position of the sun. For the climate mode these extra considerations can be useful, I am also planning to do something similar with irradiance. Btw if the control method is not equal to summer it also should default to the default value in climate mode if the weather condition is not equal to the ones you've selected.
