### ISSUE TITLE
Bug In 1.2.0-b0 Where It Still Operates Despite Being Totally Disabled

### ISSUE THREAD

**Issue by Colorado4Wheeler** [basbruss/adaptive-cover#116]
## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4989
Installed Version | 1.34.0
Stage | running
Available Repositories | 1414
Downloaded Repositories | 41

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 45

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 28, 2024 at 5:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | us-east-1-2.ui.nabu.casa
certificate_status | ready
instance_id | e4c3b0fc2d6345dd91513a760ef8ba51
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 196.2 GB
disk_used | 162.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Terminal & SSH (9.13.0), Mosquitto broker (6.4.0), Samba Backup (5.2.0), HA Command Center (0.6.0), Z-Wave JS UI (3.4.2), Check Home Assistant configuration (3.11.0), Studio Code Server (5.15.0), NGINX Home Assistant SSL proxy (3.9.0), MariaDB (2.7.1), phpMyAdmin (0.9.1), InfluxDB (5.0.0), RTSP Simple Server Add-on (v0.17.6), ESPHome (2024.4.0), eufy-security-ws (1.8.0-2), Node-RED (17.0.12)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 26
views | 64
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 5, 2024 at 4:11 PM
-- | --
current_recorder_run | April 18, 2024 at 8:55 AM
estimated_db_size | 4252.48 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When you have disabled an adaptive cover entity it still runs.  This pre-dates when you added the ability to turn off control, my solution was to just use Spook to totally disable those adaptive covers (and forgot I still had that happening on restart), and even though they are disabled they are still running automatically.  This is new to recent betas, as this process worked fine before the toggle was added.

### Reproduction steps

1. Disable an adaptive cover entity
2. Leave it and wait for automatic operations
3. This is not isolated, it occurred on three different covers
...

### Diagnostics dump

![image](https://github.com/basbruss/adaptive-cover/assets/20329385/c686a21d-5ac3-4e39-8c7e-ffcb2a9d06f7)

**Comment by basbruss** [comment]
This beta is really only supposed to test the double roller blinds. If you don’t have those you really shouldn’t run this beta because some internal code has to been rewritten to make everything work nicely :wink:

**Comment by Colorado4Wheeler** [comment]
I'll downgrade the previous version and see if it still happens.  Thanks!
