### ISSUE TITLE
Add Ability to Link to Weather

### ISSUE THREAD

**Issue by Colorado4Wheeler** [basbruss/adaptive-cover#117]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Mostly a frustration of having my smart Adaptive Cover know when there is no sun.

### Describe the solution you'd like

A nice feature to have (although with the new toggle and automation it can be accomplished in other ways) would be if you could link a weather device to Adaptive Cover with an option to ignore certain weather patterns.  I thought I saw this but after going through the settings I was mistaken.  For instance, today is raining and snowing and the sun has yet to be seen, in which case I don't need adaptive cover yet it still ran.  Since HA standardizes the major conditions it should be easy since there are only 9 or 10 conditions they summarize into and most HA compliant weather integrations honor that.

### Describe alternatives you've considered

Automation + new toggle that was added to 1.1.0

### Additional context

That's all folks.  Great add-on, I look forward to it being a huge part of my summer heat mitigation plan to save energy!

**Comment by basbruss** [comment]
Weather conditions are already part of the climate mode decisions tree, but optional based on whether you have supplied a weather entity

**Comment by Colorado4Wheeler** [comment]
I thought I saw that in there but couldn't find it, I'll dig deeper!
