### ISSUE TITLE
What is the relation of "Starting time" and "Sunrise offset"?

### ISSUE THREAD

**Issue by swa72** [basbruss/adaptive-cover#125]
### What version of Adaptive Cover are you using?

v1.1.2

### What version of Home Assistant are you using?

2024.4.3

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Not  a bug but rather a question: what is the relation of "Starting time" and "Sunrise offset"?
btw: the integration is awesome!

### Reproduction steps

1.
2.
3.
...

**Comment by basbruss** [comment]
`sunrise offset` is the minimum time after/before sunrise that the integration is allowed to control the blinds.
`start time` is the minimum time at which the integration may control the blinds. This overrides the sunrise offset if that time is before the start time

**Comment by swa72** [comment]
Great explanation, thanks. Maybe add this to the docs (and all other parameters one can tweak unless they're not self-explanatory?
