### ISSUE TITLE
Detected blocking call to import_module inside the event loop

### ISSUE THREAD

**Issue by swa72** [basbruss/adaptive-cover#134]
### What version of Adaptive Cover are you using?

1.1.4

### What version of Home Assistant are you using?

core-2024.5.0

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

See dump

### Reproduction steps

1.
2.
3.
...

### Diagnostics dump

I found this in the logs ...

```
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 16:09:56 (1 occurrences)
Last logged: 16:09:56


Detected blocking call to import_module inside the event loop by custom integration 'adaptive_cover' at custom_components/adaptive_cover/sun.py, line 26: times = pd.date_range( (offender: /usr/local/lib/python3.12/site-packages/pandas/compat/_optional.py, line 132: module = importlib.import_module(name)), please create a bug report at https://github.com/basbruss/adaptive-cover/issues
```

**Comment by basbruss** [comment]
I am aware of the issue, but for now, I can't find a solution because `pandas` itself is loading a module inside the event loop.
