### ISSUE TITLE
Minimum Position in Basic Mode

### ISSUE THREAD

**Issue by dragonXXP** [basbruss/adaptive-cover#136]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have the problem that my roller shutters have little horizontal gaps inbetween each segment, that only close when the bottom of the shutter reaches the bottom of my window.

The issue that arises with this ist that when my shutter is at around 70% it‘s already at the bottom, the remaining 30% are just for closing the little gaps inbetween the panels.

### Describe the solution you'd like

Being able to specify a minimum position that applies only to the basic mode that the integration considers fully closed would solve my issue pretty easily.

### Describe alternatives you've considered

I don’t know, I believe my primary solution would be good and also quite easy to implement.

### Additional context

A picture of the type of roller shutter I have: https://images.app.goo.gl/oGMyj3zFpetzHSum7

**Comment by basbruss** [comment]
See #129

**Comment by dragonXXP** [comment]
Oh sorry my bad, I didn’t look through the closed issues.
