### ISSUE TITLE
Option: Inverse the state won't work completly with climate data

### ISSUE THREAD

**Issue by Mikemare** [basbruss/adaptive-cover#137]
### What version of Adaptive Cover are you using?

1.1.4

### What version of Home Assistant are you using?

2024.5.1

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I work with covers which are controlled via KNX actors within my HA instance. Unfortunately I have to use the "Inverse the state" option because 100% means fully opened and 0% closed.
Basic function is working, but as soon I configure the climate parameters including all optional sensors/parameter the "Inverse the state" option wont work here. Above the "High temperature threshold" the covers open instead of closing.

I think the "Inverse the state" option isn't programmed for climate settings (Layman's opinion)

### Reproduction steps

1. Basic configuration of cover
2. activate "Inverse the state" option 
3. configure "Low/High temperature threshold"
4. High temperate open cover / low close
...

**Comment by Mikemare** [comment]
okay maybe I have a knot in my head... i don't thing my described issue is my issue.. sorry for that

the main problem is, I want to set a maximum closing position for my covers. I don't want to use "fully closed" causing stagnant heat between the roller shutter and the window. So my "fully close" and therefore maximal operation range within calculation/present/not-present should be 100%-**30%** (maximum opening position). I don't think that it possible at the moment (?)
If I am wrong, I would be grateful for any tips.

**Comment by basbruss** [comment]
You can always create a template cover that takes the info from the parent cover and convert the position to the HA convention. I will add some logic when I find time to also auto inverse the maximum position if inverse is selected
