### ISSUE TITLE
Setting sensors for forced opening (emergency override)

### ISSUE THREAD

**Issue by mlstolk** [basbruss/adaptive-cover#140]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have some local sensors that I want to use to:
- force an immediate full opening of the awning when one of the sensors is triggered
- prevent the awning from closing again for a while after one of the sensors was triggered.

You can think of a local binary sensors for 'too much wind', 'rain' warnings or other conditions, that complement the online weather services.

### Describe the solution you'd like

Adding additional options, in addition to the existing 'manual override', but for these emergency triggers:

- An additional option that allows setting a list of (multiple) sensors that would trigger the awning to open and prevent the awning from closing.
- Preferably an option to set the amount of time in which new triggers to close the awning automatically would be ignored (similar to the manual override option)
- Manual control to return to a safe state (up button for an awning) should always stay operational.
- Maybe a switch to set if manual control to a non-safe state should still be possible. 

### Describe alternatives you've considered

I considered using the manual override options, but I think it would be beneficial to separate these emergency opening conditions and regular manual override.

### Additional context

n/a

**Comment by basbruss** [comment]
> I have some local sensors that I want to use to:
>   - force an immediate full opening of the awning when one of the sensors is triggered
>   - prevent the awning from closing again for a while after one of the sensors was triggered.
>
>You can think of a local binary sensors for 'too much wind', 'rain' warnings or other conditions, that complement the online weather services.

You can easily automate this by triggering on those sensors. Turning off the `adaptive control switch` and set the correct cover action. Afterwards, when appropriate you can turn the  `adaptive control switch` `on` again and everything should work again.

**Comment by mlstolk** [comment]
Ah, thank you for suggesting this. It seems like a plausible solution to what I want to accomplish; great!

**Comment by Colorado4Wheeler** [comment]
@mlstolk you might be interested in a post I made on the HA forum: https://community.home-assistant.io/t/what-is-your-most-useful-automation/648543/86.

I've really tricked out (i.e., totally geeked out) my curtain control to do things based on conditions and events and incorporated into it the adaptive cover features, like turning on or off the toggle based on other conditions or if it's in sun, etc.

The idea is setting up a sensor with a JSON of your various settings.  Then I have two scripts, one is the actual brain that does the work and the other is simply something that goes through every cover and runs the brain function.  For instance, I pre-set all the settings for when we awake, any cover that has an awake setting gets set.  As a use case for you, an event could be "emergency" where all covers open to 100%.  Doing this all my covers open at almost the exact same time to precisely where i want it to be.

Happy to talk further about this if you want, just DM me on HA.

**Comment by mlstolk** [comment]
Thank you very much @Colorado4Wheeler for bringing this to our (my) attention in relation to this question. A very interesting approach indeed.
