### ISSUE TITLE
Changing Setting(s) Forces Adaptive To Run Even When Disabled

### ISSUE THREAD

**Issue by Colorado4Wheeler** [basbruss/adaptive-cover#142]
### What version of Adaptive Cover are you using?

1.1.3

### What version of Home Assistant are you using?

2024.4.4

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

If you have disabled the toggle control on an Adaptive cover and change the settings for the cover, it will run.  The expectation is that the settings save and apply but the cover still honors the toggle state.

### Reproduction steps

1. Disable an Adaptive Cover
2. Change the settings on the cover (in my case it was the left angle via Fine Tune)
3. Submit the change
4. Adaptive runs
...

**Comment by basbruss** [comment]
Thanks! Never noticed it but was able to reproduce. Fixed with #143
