### ISSUE TITLE
Add blind spot including elevation

### ISSUE THREAD

**Issue by nameetpai** [basbruss/adaptive-cover#145]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Two sides of my house have windows along the fence line and neighbor's houses on the other side. The adaptive cover settings I've configured work perfectly for when the sun is unobstructed by neighbor's houses and the fence. However, during sunrise and sunset my vertical shades on each side of my house close fully when instead, they should just open fully to let light in because it's only diffuse light coming in. The sun is fully blocked at those times.

### Describe the solution you'd like

Just like there's settings to specify distance of work area from bottom of cover, need a way to specify distance of fence line or other obstruction from top of cover. Can use that measure to calculate when the sun is no longer detected outside the window.

### Describe alternatives you've considered

Alternative is to have a timed automation based off of offset from sunset (maybe a couple hours before) that turns off adaptive control and fully opens the shades until sunset. I could tune this somehow with trial and error but seems inelegant to have multiple automations for this when adaptive cover is so close to perfect.

### Additional context

None

**Comment by basbruss** [comment]
You can adjust the FOV left/right settings to filter for large objects at the sides. Since you talking about sunset and sunrise times I guess this could work for you. See also this post for reference https://community.home-assistant.io/t/automatic-blinds-sunscreen-control-based-on-sun-platform/573818/191

If not a blind spot area within the field of view can be considered to implement in the codebase.

**Comment by nameetpai** [comment]
FOV left/right unfortunately doesn't work for me because the two sides of my house are precisely East/West azimuth so the sun rises almost vertically on one side of the house and sets almost vertically on the other. The fence lines are perfectly parallel to the two sides of the house so what I really need is what I described above. Distance from top of cover to fence. Almost like a FOV up/down if that makes sense. I can draw this out if it isn't clear.

**Comment by basbruss** [comment]
So what you really need is between azimuth x and y and if the sun is lower than elevation z return to default value if I understand correctly. A drawing always helps to grasp the situation more correctly:)

**Comment by nameetpai** [comment]
You got it! That works for me and would probably work for most others with the same problem. Default value for me is 100% which is what I want. But everyone sets default value to their preferred setting when the sun is not directly on the window so that makes perfect sense.

**Comment by travisp** [comment]
Not sure if this is a separate feature request, but I think a FOV up/down would be really helpful.

I live in a high rise apartment and the sun is blocked by buildings as it sets. In addition, some of my windows essentially have an awning sticking out above them (there's a balcony sticking out over it), blocking the sun when it is high. Not sure how common the second one is, but I would image that the first (sunset or sunrise blocked by hill or building) is relatively common.
