### ISSUE TITLE
Add external entity override for automatic cover positioning 

### ISSUE THREAD

**Issue by momab** [basbruss/adaptive-cover#157]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have set the vertical outside blinds to automatically go up and down depending on the position of the handle Sensors on the window handles. 
whn I set the handle to „open“, the blind completely stays open. 
all blind automations I had before then do not set the blind position when the handle is open, to minimize the risk of someone getting their head chopped of, getting locked out on the balcony or breaking the blind when the movable AC has its hose hanging out of the window. 

### Describe the solution you'd like

I would like the ability to set some kind of override for specific entities, like the handle position or a Boolean entity. 

### Describe alternatives you've considered

Setting up a timer, which presses the reset button every 14 minutes, for as long as the handle is in the „open“ position. 

### Additional context

If you need any more info, I will give you anything you need.

**Comment by basbruss** [comment]
For these cases, the Adaptive Toggle Control switch is added, allowing you to automate when adaptive control is preferred based on your personal preferences. Incorporating such control management within the integration is cumbersome and makes it difficult to introduce a one-size-fits-all solution for the various cases that should disable adaptive control. However, automating the switch is far easier and potentially better optimized to your personal preferences.

**Comment by craigwitter** [comment]
I would like to see an external input variable to provide control of the adaptive control as well. My use case is fairly simple. I wouldn't want it to close the shade when the window is open. Each of my windows have contact sensors on them, so home assistant knows whether they're open or not.  I realize I can do an automation that could switch the override off and on, but it would be a nice to have all in one place, vs having to maintain another automation. Thanks for the great work!

**Comment by basbruss** [comment]
@craigwitter To implement such a feature that works for most people we need to account for very different situations or moments when the state of an entity should be evaluated, that is too complex to integrate, while on a user level a simple automation is the easy solution.

For example: to what state should it listen? Should it open, should it close, should it go to the default position, should it stay at its current position, should it go to another specified position?
