### ISSUE TITLE
Add strategy for see-through blinds to always close fully in summer mode.

### ISSUE THREAD

**Issue by bend** [basbruss/adaptive-cover#163]
### What version of Adaptive Cover are you using?

1.1.4

### What version of Home Assistant are you using?

2024.5.3

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have setup a couple of covers at home but they act weird.
Let's take one example of a store
Control Method: summer
Cover Position: 4%
End Sun: In 5 hours
Manual Override: Not running
Start Sun: 5 hours ago
Sun Infront : Detected

Climate mode activated, presence mode not activated and external temperature activated.
The temperature of the internal sensor is 24C and the minimal temperature is 19 and maximal temperature is 21C
The external temperature is 24.5C
The weather is sunny.

Hence I don't understand why the cover remains open at 4%, for me it should be fully closed.

### Reproduction steps

Setup an automatic cover with an external temperature sensor, internal temperature sensor, weather.
Wait for the cover to be exposed to the sun, weather sunny, high temperature inside and outside (above the max range of the confort temperature)
Expectation: Cover should be closed
Actual: Cover is opened at 4%

**Comment by basbruss** [comment]
Can it be that the minimal delta position is preventing it to go from 4 to 0 zero?

**Comment by bend** [comment]
![Screenshot_20240523-140220](https://github.com/basbruss/adaptive-cover/assets/471132/a5927a26-95f8-4b8c-a43b-25f2db647262)
Everything is set to the minimum

**Comment by basbruss** [comment]
> presence mode not activated

With this do you mean that you have not set up a presence sensor or that the state of that sensor indicates a deactivated mode?

**Comment by bend** [comment]
@basbruss Indeed no presence sensor, and the minumum delta to move the store is set to 1% and 2 minutes

**Comment by basbruss** [comment]
Ah okay, that is the origin of the misleading position. When there is no presence sensor set it assumes there is always presence. Therefore we should first focus on blocking direct light rays while allowing natural light to come in. So even in summer mode the cover will return to the calculated optimal position that holds both conditions. If there is no presence we don't care about natural light coming into a room, so than the cover can close fully within summer mode.

**Comment by bend** [comment]
my covers are solar covers, so they let the light in by retaining UVs and heat. so it should be closed even is someone is at home to avoid the house to heat too much. 
What should I do to configure that ?

**Comment by bend** [comment]
If I set a presence detector, it means covers will only close if I'm not home ?

**Comment by basbruss** [comment]
Or add a dummy `input_boolean` that always returns `off`. I can add a strategy option for see-through covers that block UV and heat to close fully in summer mode with presence. Do you mind if I change this issue to a Feature request for that?

**Comment by bend** [comment]
@basbruss  yes go ahead. I will do that in the meantime :)
Thanks for your help

**Comment by bend** [comment]
@basbruss  do you have any documentation on how the Control method is calculated ? (Summer, Intermediate, Winter)
Thanks

**Comment by bend** [comment]
I've set the presence with a binary sensor like indicated I have the following now:
![image](https://github.com/basbruss/adaptive-cover/assets/471132/f4d4f62d-8bf4-44a3-b380-f8d382fda724)
Covers stays opened, but sun is detected

**Comment by basbruss** [comment]
> @basbruss do you have any documentation on how the Control method is calculated ? (Summer, Intermediate, Winter) Thanks

https://github.com/basbruss/adaptive-cover/blob/eea556dc2b7dbd4607629ffce2a596358d5ed6b9/custom_components/adaptive_cover/calculation.py#L219C4-L224C21

So basically when the reference temperature is above the maximum comfort temperature.



> I've set the presence with a binary sensor like indicated I have the following now: ![image](https://private-user-images.githubusercontent.com/471132/333201936-f4d4f62d-8bf4-44a3-b380-f8d382fda724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzI2NTYsIm5iZiI6MTcxNjQ3MjM1NiwicGF0aCI6Ii80NzExMzIvMzMzMjAxOTM2LWY0ZDRmNjJkLThiZjQtNDRhMy1iMzgwLWY4ZDM4MmZkYTcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMzUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzIzMjJjY2Q0NTBiNDY2OGU3ZDI3NTRjYmIxNGI0M2ZkYmZkYzRlZTMzYTczMzBmZWFkYzZhMTNkMGFiZTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WeNns6BZ_D4gW06KJgzgRp8SZW997W3ozlhzm9rrpE4) Covers stays opened, but sun is detected

Yes, that is right since the control method is indicating `intermediate` or in other words the measured temperature is within the minimal and maximum comfort temperature range. Resulting in normal adaptive behaviour.

**Comment by basbruss** [comment]
The control method is based on the strategy used in this paper
https://www.mdpi.com/1996-1073/13/7/1731

**Comment by bend** [comment]
@basbruss outside temperature and inside temperature are both higher than max temp set, the weather temp however is at 19. So I guess there is a prioroty on the weather temperature ?

I've changed the max and min value to very low values and now it is in summer mode however covers stays at 0% (even though I've waited enough time to be sure that automation gets triggered).

**Comment by basbruss** [comment]
> outside temperature and inside temperature are both higher than max temp set, the weather temp however is at 19. So I guess there is a prioroty on the weather temperature ?

That is `true`, now I look at it, it could be better to prioritize the outside temperature sensor over the weather attribute.

Yes, 0% means fully closed and is therefore the wanted state in summer mode.

**Comment by bend** [comment]
Do you have a discord so we can discuss that ? Something not clear for me.

**Comment by basbruss** [comment]
Yes same name tag as here on github
