### ISSUE TITLE
Add minimum position for covers

### ISSUE THREAD

**Issue by bend** [basbruss/adaptive-cover#171]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When sun is detected and weather is summer, the covers close completely even though it's not necessary to close it completely

### Describe the solution you'd like

A minimum position value that works the same as the maximum position that allows a cover to close at a max position. 

### Describe alternatives you've considered

Openning manually

### Additional context

No context

**Comment by miezie** [comment]
This is a really good addition to put shutters at a defined minimum to put them in "ventilation mode" which is better on sunny days where the temperature between glass and shutter increases a lot. Ventilation mode limits this quite a bit and gives overall a good result for temperature comfort next to sun protection.

**Comment by basbruss** [comment]
Let's start a discussion topic for this to see if and how this can be implemented. Because a minimum position is prone to reduce the glare-reducing feature on the work area, which is ultimately the main goal of this integration. Also on summer days, the sun will rise higher than on other days, so based on the geometrics the cover is not fully closed, but even higher than on winter days due to the larger elevation angle, which also should allow for some ventilation.

**Comment by miezie** [comment]
@basbruss for me it is about the "ventilation mode" of a shutter which means that you open up a very little to see the small holes between the blinds. I programmed this as a favorite position in my somfy tahoma where shutters are opened for 15% (which means closed with holes). Currently I just have an automation to do this when the component closes for <15% and I start overruling. 
I think it mainly means that the calculation of the amount of closing is impacted. For me it fits more in the option to fully close in summer mode. :-)

**Comment by basbruss** [comment]
@miezie Okay that is a slightly different use case than a pure minimum position. Also note that since v1.3.x there is an interpolation feature which allows you to map the close and open positions for shutters that do not open linearly (in terms of vertical position) from 0% to 100%, but for instance, first open the holes and start really opening at for example 15%.

**Comment by basbruss** [comment]
Here you can find the discussion topic https://github.com/basbruss/adaptive-cover/discussions/225

**Comment by miezie** [comment]
I will first validate your proposal... Creating a bug report for that one now:  #226

**Comment by miezie** [comment]
@basbruss can you elaborate on how to use the interpolation features? I really don't get it :).

**Comment by basbruss** [comment]
@miezie Do you need a two-point interpolation or multiple-point interpolation?
The first one uses both sliders. So you mentioned the blinds start to open at `15%`, so you can set the first slider to that value. So let's say, the blinds stop opening at `85%` You can put that on the second slider.

If the blinds do not have a linear scale between the adjusted start and end points, you can add more points with the list options underneath (these override the above sliders). There you can set a list to correspond with a linear scaled list. So for example you have a cover that starts opening at `15%`, is halfway open at `60%` and stops opening at `85%`, then you can set the first list to the normal corresponding ha values, so start=0 halfway=50 and end=100, in the second list you at the above value: start=15 halfway=60 end=85. You can extend this example with as many points as you need to scale it correctly.

**Comment by miezie** [comment]
Does the trick for me! Ventilated always 🥰

**Comment by miezie** [comment]
As an addition: when not home I think interpolation is not applied… am I correct?

**Comment by miezie** [comment]
> As an addition: when not home I think interpolation is not applied… am I correct?

With the addition of #254 I noticed that positions are not taken into account when not at home. So that by defintion everything just closes. I think this is not the intention. Right?

**Comment by miezie** [comment]
> > As an addition: when not home I think interpolation is not applied… am I correct?
> 
> With the addition of #254 I noticed that positions are not taken into account when not at home. So that by defintion everything just closes. I think this is not the intention. Right?

Fixed in 1.4.2 I noticed. To me this one can be closed!
