### ISSUE TITLE
AdaptiveHorizontalCover not using `height_awning`

### ISSUE THREAD

**Issue by mion00** [basbruss/adaptive-cover#175]
### What version of Adaptive Cover are you using?

1.2.0

### What version of Home Assistant are you using?

2024.5

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

From the source code, it seems as if the config entry `height_awning` is not used in any way by the `AdaptiveHorizontalCover`.
Maybe it was used in a previous version of the `calculation.py`?

### Reproduction steps

Searched the source code for reference to the `CONF_HEIGHT_AWNING` constant.

**Comment by basbruss** [comment]
Thanks for mentioning this, I will take a closer look at in when I have more time. It could be that the value used in the calculation is not correct.
