### ISSUE TITLE
No trigger to move cover

### ISSUE THREAD

**Issue by swa72** [basbruss/adaptive-cover#180]
### What version of Adaptive Cover are you using?

1.2.0

### What version of Home Assistant are you using?

2024.5.5

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have set an entity to determine start time (_Start Time Entity_). I would assume that at this point in time the automation sets the cover to its default position of 85% (_Default Position, Initial position of the cover in the absence of sunlight glare detection_). In my case, the cover did not move.

![image](https://github.com/basbruss/adaptive-cover/assets/17599763/3eba40f3-2bb5-466c-8ed0-2fd9904e6d9c)

Start time entity is a helper with 

```
has_date: false
has_time: true
editable: true
hour: 8
minute: 0
second: 0
timestamp: 28800
friendly_name: cover_result
```

### Reproduction steps

1.
2.
3.
...

**Comment by basbruss** [comment]
The time is not a trigger for that time. It only prevents adaptive changes before that time. So it starts changing after that time, but not directly on the time itself.

**Comment by swa72** [comment]
Ok, misinterpreted the docs ;-) You may want to add something to the start time description.

**Comment by basbruss** [comment]
Always happy to accept improvements by a Pull request :wink:
