### ISSUE TITLE
Unknown string format: sensor.sun_next_setting

### ISSUE THREAD

**Issue by akula3** [basbruss/adaptive-cover#182]
### What version of Adaptive Cover are you using?

1.2.0

### What version of Home Assistant are you using?

 Core 2024.5.5 Supervisor 2024.05.1 Operating System 12.3 Frontend 20240501.1

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Define sensor.sun_next_rising for "Entity indicating starting time" is allowed, whereas define sensor.sun_next_setting for "Entity indicating ending time" is not allowed

### Reproduction steps

1.
2.
3.
...

### Diagnostics dump

Logger: homeassistant.config_entries
Quelle: config_entries.py:584
Erstmals aufgetreten: 26. Mai 2024 um 23:53:21 (4 Vorkommnisse)
Zuletzt protokolliert: 08:37:48

Error setting up entry Vertical Küche for adaptive_cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/__init__.py", line 60, in async_setup_entry
    end_time = get_datetime_from_str(_end_time_entity)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/helpers.py", line 34, in get_datetime_from_str
    return parser.parse(string, ignoretz=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: sensor.sun_next_setting

**Comment by basbruss** [comment]
What is the format of the state of the sensor?

**Comment by akula3** [comment]
I assume, hte format of sensor.sun_next_setting should be the same like from sensor.sun_next_rising.
I'm using the regular Sun integration from HA.
This is the current state from sensor.sun_next_setting:
![grafik](https://github.com/basbruss/adaptive-cover/assets/58461189/f34b566d-5ed1-4958-a16e-26e92a4b3fca)
Hope, that helps.
