### ISSUE TITLE
Adaptive Cover ignoring Weather Condition

### ISSUE THREAD

**Issue by age-creator** [basbruss/adaptive-cover#184]
### What version of Adaptive Cover are you using?

1.2.1

### What version of Home Assistant are you using?

2024.5.5

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When specifying the weather conditions this isn't taking into account. Adaptive Cover is always moving the cover to the position based on the sun location (and does this perfectly!)

### Reproduction steps

1. Configured Weather entity with condition
2. Configured specific Weather Conditions
3. Horizontal Climate Mode is On
4. Adaptive Cover is moving cover while current weather condition is different than the configured weather conditions.

**Comment by basbruss** [comment]
@age-creator Weather conditions are only used in `winter` and `intermediate` and not in `summer` mode. Could it be that your climate control mode is in `summer` mode right now?

**Comment by age-creator** [comment]
@basbruss thanks for your prompt response, that indeed was the case. Wasn't aware of that trigger.
