### ISSUE TITLE
Not a valid add-on repository

### ISSUE THREAD

**Issue by colethorsen** [basbruss/adaptive-cover#186]
### What version of Adaptive Cover are you using?

github

### What version of Home Assistant are you using?

Core 2024.5.5 Supervisor 2024.05.1 Operating System 12.3 Frontend 20240501.1

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When attempting to add the repository an error appears:
https://github.com/basbruss/adaptive-cover is not a valid add-on repository

Other custom repositories can be installed without issue.

### Reproduction steps

1. install HACS
2. restart
3. Navigate to Settings > Add Ons > Add-On Store > ... > Repositories
4. input `https://github.com/basbruss/adaptive-cover`
5. Error is returned: `https://github.com/basbruss/adaptive-cover is not a valid add-on repository`
...

**Comment by Eskander** [comment]
This is a _custom integration_ not an _add-on_, therefore you need to add it under HACS: https://hacs.xyz/docs/faq/custom_repositories/
