### ISSUE TITLE
Cover does not change its position

### ISSUE THREAD

**Issue by Kejszijo** [basbruss/adaptive-cover#195]
Hi,

I set up this intgration, and I get Vertical Cover Position xxxxx. When I set it first, the cover set the position. But after every change, the cover position not change. Did I miss something in the setup?

![image](https://github.com/basbruss/adaptive-cover/assets/13425330/2df52858-da16-45cf-a3e4-2f3b915d44d2)

![image](https://github.com/basbruss/adaptive-cover/assets/13425330/f2cd317d-1bd4-4258-a6f9-34b5cbccec4a)

![image](https://github.com/basbruss/adaptive-cover/assets/13425330/5b81dacb-3aae-44fb-81fd-90b3ab180ee4)

![image](https://github.com/basbruss/adaptive-cover/assets/13425330/03fec573-7387-4ddb-95e7-949997a87a06)

![image](https://github.com/basbruss/adaptive-cover/assets/13425330/9fd64858-a239-4837-a8bd-da35eda6236b)

**Comment by basbruss** [comment]
Does v1.2.2 fix this issue for you?

**Comment by Kejszijo** [comment]
Yes, thank you!
