### ISSUE TITLE
Ac cover position isn't the same as screen position

### ISSUE THREAD

**Issue by ghost** [basbruss/adaptive-cover#202]
### What version of Adaptive Cover are you using?

1.2.2

### What version of Home Assistant are you using?

2024.6

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I use the adaptive cover integration with a screen. The ac cover position is 0%, but when I check the position with the screen, the screen is at 4%. The screen position is correct because of the gap I see, the screen isnt closed fully..

### Reproduction steps

1. 
2.
3.
...

**Comment by basbruss** [comment]
Please provide some more info, what are your automation settings? What are your defaults? Did you run some debugging on the integration? Do you have a graph of the position so I can estimate where in the cycle the cover should be?

Just stating that the position is not aligned is not enough to help you.

**Comment by ghost** [comment]
Here are some automation setrings in Dutch:
Minimale positieaanpassing*

10
10
%
Minimale verandering in positie vereist voordat de positie van de bekleding wordt aangepast

Minimale interval tussen positieveranderingen
5
minutes
Minimale tijdsinterval tussen positieveranderingen; minimum is 2 minuten

So in percentage it changes if its bigger than 10% and after 5 minutes. If the percentage is below 10% and when 5 minutes is passed is the screen adjusted to the new percentage?

**Comment by basbruss** [comment]
No both conditions need to be true, so it can be that the last value was 4% and it changes to 0%, but the cover is not adjusted because the delta is lower than the 10% threshold.

But I also think that the cover should always be able to return to the specified default value regardless of the minimale positie verandering. So in that sense this could be a bug.

**Comment by ghost** [comment]
Now both conditions needs to be true. For zwave devices I often see similair conditions and they behave a little bit different. If one if the conditions is true it is executed. Maybe we can add a 'or' or an 'and' condition for the 2 conditions in the configuration?
