### ISSUE TITLE
Upgrade from 2.x to 3.0 changes behavior

### ISSUE THREAD

**Issue by Colorado4Wheeler** [basbruss/adaptive-cover#214]
### What version of Adaptive Cover are you using?

1.3.0

### What version of Home Assistant are you using?

2024.6.3

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I updated this morning to 1.3.0 and my covers started acting differently without any config changes.  For example, in this case, the blind should be open to a max of 25% but it keeps opening to 70% - which is odd because while that is the max for most of my curtains you can see that is not the case here.  It must be picking this up somewhere because it would be 100% if just default.

Settings:

![image](https://github.com/basbruss/adaptive-cover/assets/20329385/544e9b91-aa94-473f-a2af-d7e444e21fe6)

And it keeps opening to 75%

![image](https://github.com/basbruss/adaptive-cover/assets/20329385/736dab7e-326c-4fc0-971d-d29e44a74cbd)

This has been working fine for quite some time but all my shades now are totally different, forcing me to either spend hours debugging and redoing my various triggers based on this system or downgrade back to 2.x.

### Reproduction steps

I really don't know how to reproduce it, because I don't know why it's suddenly ignoring my min/max even though I have re-saved my prefs again.

**Comment by dieneuser** [comment]
I can confirm the problem, the position values ​​are no longer correct for me either (my default/max positions are 100%) - it looks as if the values ​​are inverted. The lux control also doesn't work - the logic seems to be faulty (int vs float).
I went back to the previous version (1.2.2).

**Comment by Andzej-Buncol** [comment]
The same behaviour in my HA 2024.5.5
I also spent more than an hour trying to figure out why shades working like inverted.
I also went back to 1.2.2

**Comment by Colorado4Wheeler** [comment]
Reverting back to 1.2.2 sets it right again.  I agree with @Andzej-Buncol that it almost acts inverted, it went from 75% that it should **not** be to 25% where it should be:

![image](https://github.com/basbruss/adaptive-cover/assets/20329385/96b5ac19-99bc-4ce3-a229-412214d9b22c)
