### ISSUE TITLE
At maximum position the motor is still activated

### ISSUE THREAD

**Issue by ghost** [basbruss/adaptive-cover#222]
### What version of Adaptive Cover are you using?

1.3.1

### What version of Home Assistant are you using?

2023.6.3

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When the screen is at maximum position (100%), i hear the screen controller clicking, which means that the controller gets a command. This clicking interval is the same as the configured interval.

Does the code/integration check if the screen is in maximum position?

### Reproduction steps

1. Configure Adaptive Cover
2. Wait until ir reached the maximum calculated position 
3. Listen if you hear the controller clicking
...

### Diagnostics dump

I try to get one

**Comment by ghost** [comment]
Looks like version 1.3.2 solves this issue

**Comment by ghost** [comment]
I was wrong. When the screen is closed (0%), the screen switch is clicking every 2 minutes. The minimal posotion change is 10% and the minimal time change is 5 minutes.

**Comment by basbruss** [comment]
Thanks, I added a check to all service calls to see if the cover is already in the correct position.

**Comment by ghost** [comment]
Solved
