### ISSUE TITLE
Add door sensor's to disable closing

### ISSUE THREAD

**Issue by Pepeanuts** [basbruss/adaptive-cover#241]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

My cover is for a door so i'm blocked outside when my door is open and my cover is closing

### Describe the solution you'd like

Add in settings the possibility to add a door sensor to disable cover closing after sunset.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by basbruss** [comment]
This appears to be a personal issue that can be easily addressed with a simple automation using the provided entities. However, the challenge is that incorporating such an entity requires the integration to handle multiple scenarios that could disable the adaptive function or cause it to stick to a fixed position. Accounting for all possible needs would be too complex.
