### ISSUE TITLE
Allow "group" to be set to pressence detection

### ISSUE THREAD

**Issue by Lipown** [basbruss/adaptive-cover#242]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

More people occupy home but I am not able to fill in all in the _presence entity_ form.

I have created group of all persons which reports the 'home' status if anybody is home. But I am not able to set this group to that form.

### Describe the solution you'd like

Allow to put there a group entity.

### Describe alternatives you've considered

I will try to check if binary sensor can do similar output as group.

### Additional context

![image](https://github.com/basbruss/adaptive-cover/assets/57076375/c18a0ded-3ab3-4719-89c0-87afa4758504)

**Comment by miezie** [comment]
This just works when you create a binary sensor helper doing the same as a group? Just implemented it these days... (and took away a load of automations...).

**Comment by basbruss** [comment]
@Lipown There is no need to use a group to determine if someone is home. The `zone.home` entity does this already for you if you have the device trackers and persons set correctly

**Comment by Lipown** [comment]
@basbruss thank you! :)
