### ISSUE TITLE
How do I find out my window azimuth?

### ISSUE THREAD

**Issue by ars4l4n** [basbruss/adaptive-cover#255]
I need an explanation that is more detailed than [that](https://doc.forecast.solar/find_your_azimuth). 
What am I supposed to do with the compass? I find it odd that everyone takes it for granted that people know how to do that. I know nobody that has any idea about this.

**Comment by basbruss** [comment]
Those guides describe perfectly how to find the window azimuth, just set the compass perpendicular to the side of the window and read the value. North is always 0 degrees and South is 180 degrees.

**Comment by miezie** [comment]
Or just put the compass of your phone against the window pointing to the outside in horizontal position. On an iPhone you see the degrees…

**Comment by aaronstaves** [comment]
@ars4l4n 

It's in the README [here](https://github.com/basbruss/adaptive-cover?tab=readme-ov-file#setup), however it's described in much more detail in a post on the [homeassistant community forums
](https://community.home-assistant.io/t/automatic-blinds-sunscreen-control-based-on-sun-platform/573818#finding-the-window-azimuth-what-direction-your-window-points-5)

**Comment by ars4l4n** [comment]
Those guides didn't specify though that the compass arrow, specifically the one that doesn't point north, needs to be pointed away from the window as if you were looking outside of it. @miezie 's answer made me get it.

**Comment by ggonmar** [comment]
I came to find this thread looking for the same explanation.
Window Azimuth means then the complete perpendicular of the window? I initially considered it was the first moment the sun would start hitting (even obliquely) the window. 
I think a diagram would solve our doubts....!
