### ISSUE TITLE
Would you add the option to set the distance between the cover and the shaded area to a lower value?

### ISSUE THREAD

**Issue by ars4l4n** [basbruss/adaptive-cover#261]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

In my case, the distance between the blinds and my window is lower than the minimum of 0,1m the intergration allows you to enter, so I entered the value inaccurately.

### Describe the solution you'd like

Setting the distance to 0,05m.

### Describe alternatives you've considered

None.

### Additional context

-

**Comment by basbruss** [comment]
If you set the distance too low, it will cause problems because the horizontal line and the sloped side of the triangle don't have any space between them. This makes it impossible to find where they intersect, often resulting in a zero distance, which is incorrect.
