### ISSUE TITLE
Only Sunrise/sunset

### ISSUE THREAD

**Issue by Kejszijo** [basbruss/adaptive-cover#285]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi,

I want to use this integration only control my cover for sunrise (full open) and sunset (full close)
I figure out, if I set the "Minimum position adjustment" to 90% in Automation config, and  "minimum position" to 99% and checked the "Only force the minimum position when the sun is in front of the window" in Fine-tune setting, the sunset works fine. The cover closed fully.
But sunrise is opened to 1%.
Is that possible to open a cover to 0%?

### Describe the solution you'd like

Maybe if the minimum position can be set to 100%?!

### Describe alternatives you've considered

new checkbox for only sunset/sunrise

### Additional context

![image](https://github.com/user-attachments/assets/10b8ea18-a563-4853-8d87-59a7961c2b64)
![image](https://github.com/user-attachments/assets/a019a4f7-571d-4ed5-ac0b-4528783b5245)
![image](https://github.com/user-attachments/assets/428571f4-5d4d-4be5-b7b9-03cc908400b3)

**Comment by basbruss** [comment]
Hi @Kejszijo 

If you only want to adjust the positions of your covers at sunset and sunrise you can build a simple automation within HA with the built-in [sun component](https://www.home-assistant.io/integrations/sun/).

This integration is intended to be used adaptively throughout the day and therefore doesn't account for your needs.
