### ISSUE TITLE
“Minimum position” affects "Sunset Position"

### ISSUE THREAD

**Issue by SirSheik** [basbruss/adaptive-cover#287]
### What version of Adaptive Cover are you using?

1.4.3

### What version of Home Assistant are you using?

2024.8.1

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hello.
First of all thank you for this integration, I am a long time user of your previous blueprint and it is great. 
I would like to migrate all my blinds to this integration but unless it is my fault of configuration I found a bug.
I have found that when the “Minimum Position” field is set to a value other than 0% this field affects the “Sunset Position” and I believe that they should be independent positions and not affect each other.

### Reproduction steps

Set the following values in the integration:
- Default Position = 100%
- Minimum Position = 40% 
- Sunset Position = 20% (Any position below “Minimum Position”)
_*Climate mode deactivated to exclude other variables_

The blinds after sunset changes from the default value 100% (No sunshine) to 40% but not to the position set as “Sunset Position”.
Which indicates to me that the “Minimum Position” field is also affecting the “Sunset Position”.

![Image 061](https://github.com/user-attachments/assets/af095207-ded0-4726-a36c-207c71c9d597)
![Image 063](https://github.com/user-attachments/assets/dedc5d71-7399-45f0-aacb-ab5bb231c919)
![Image 064](https://github.com/user-attachments/assets/63874cb5-cabe-4a35-b0a7-a51c270b5311)

**Comment by basbruss** [comment]
If you select the checkbox underneath the minimum position (`only force minimum position when the sun is in front of the window`) the minimum position should not influence the (sunset)default positions.

> I have found that when the “Minimum Position” field is set to a value other than 0% this field affects the “Sunset Position” and I believe that they should be independent positions and not affect each other.

Without the checkbox selected both positions aren't independent since some situations should always be open to x% even though some default value is wrongly given.

**Comment by SirSheik** [comment]
> If you select the checkbox underneath the minimum position (`only force minimum position when the sun is in front of the window`) the minimum position should not influence the (sunset)default positions. [Si selecciona la casilla de verificación debajo de la posición mínima (solo forzar la posición mínima cuando el sol está frente a la ventana), la posición mínima no debería influir en las posiciones predeterminadas (puesta de sol).]
> 
> > I have found that when the “Minimum Position” field is set to a value other than 0% this field affects the “Sunset Position” and I believe that they should be independent positions and not affect each other.
> 
> Without the checkbox selected both positions aren't independent since some situations should always be open to x% even though some default value is wrongly given. [Sin la casilla de verificación seleccionada, ambas posiciones no son independientes ya que algunas situaciones siempre deberían estar abiertas al x% incluso si algún valor predeterminado se proporciona incorrectamente.]

Great. Thank you very much for that tip.
I'll try it this afternoon and confirm again here.
Thank you very much for your quick help.
Have a nice day.

**Comment by SirSheik** [comment]
Thank you very much the solution worked fine.
The solution was check the option.
“Only force the minimum position when the sun is in front of the window”
Thx
