### ISSUE TITLE
Contact Sensor Setting

### ISSUE THREAD

**Issue by MRobi1** [basbruss/adaptive-cover#309]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

When a window is open, it's nice to have the blinds open to keep them from flapping around in the wind and to allow for better airflow.

For windows with contact sensors, it would be nice to have the ability to program a blind position based on the state of the contact sensor. It could be as simple as defining the contact sensor, and having a "set blind to X position when contact sensor open". 

### Describe alternatives you've considered

This is currently do-able by maintaining a separate automation that disables blind control when the contact sensor is open and sends a command to open the blind. Then re-enable blind control when closed. But that requires maintaining a separate automation for something that will likely be a common use-case for blinds. 

### Additional context

Would be nice to have all blind controls in 1 spot without a separate automation.

**Comment by basbruss** [comment]
See https://github.com/basbruss/adaptive-cover/discussions/290
