### ISSUE TITLE
Add "maximum" open setting so that roman shades don't try to open all the way

### ISSUE THREAD

**Issue by tuday2** [basbruss/adaptive-cover#39]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have roman shades that can't/shouldn't go up more then 60%... I can set the default but often times it will open them to 100% which isn't good for the blinds as they aren't really made to fold up that far. 

### Describe the solution you'd like

Can a max "raise" height be set to override the maximum cover % it will open too , for me I want it to stop at 60% and be considered "fully open"

### Describe alternatives you've considered

Somehow changing the sensor but figured I can't be the only ones that needs this.

### Additional context

none

**Comment by basbruss** [comment]
This could be implemented in two ways I guess.
1. Add the logic to the sensor and add the option in the option/config flow
2. Add a fallback in the blueprint and leave the sensor value untouched:
```jinja
{% set max_height_per = 60 %}
{{ iif(states('sensor.adaptive_cover')|int > max_height_per, max_height_per, states('sensor.adaptive_cover')) }}
```
I think I prefer the second option. What do you think?

**Comment by tuday2** [comment]
Yeah the blueprint option makes sense

**Comment by basbruss** [comment]
@tuday2 Btw this is already possible by using the condition selector in the blueprint.

```yaml
condition: numeric_state
entity_id: sensor.adaptive_cover
below: 61
```

This also prevents any state change above 60

**Comment by tuday2** [comment]
Oh --- i didn't realize that. I think I would put Above 60 though -- since it is what prevents changes? Here is what I did (will know this afternoon if this works)

![image](https://github.com/basbruss/adaptive-cover/assets/27604078/49327f60-7c64-4d88-9e34-648a03254958)
