### ISSUE TITLE
Bidirectional Tilted Blinds should start at 50% not 0% for some devices

### ISSUE THREAD

**Issue by AwesomenessZ** [basbruss/adaptive-cover#6]
## System Information

version | core-2023.10.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.57-1-lts
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1321
Downloaded Repositories | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 21
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 20, 2023 at 12:05 AM
-- | --
current_recorder_run | October 26, 2023 at 2:07 PM
estimated_db_size | 379.03 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Thank you for creating this integration, it makes it as easy as possible to deploy these calculations to a sensor!

Currently, when using tilted blinds in Bidirectional mode with my SwitchBot Tilt devices, they start at 0% (Closed down) and move to a peak of 50% (fully open) when the sun is the strongest. After that, they move back down to 0% (fully closed down) as the sun moves off of them.

What I would like to have an option for is to have this occur in the upper range of the bidirectional mode. So start at 50%, peak at 100% when the blinds need to be fully closed (facing up) as they are getting a lot of sun, and then move back to 50% (open) as the sun is not hitting them as much.

Would it be possible for you to implement this as a setting if it is not a bug for all users?

Thank you!

### Reproduction steps

1. Setup a Bidirectional Tilted blind
2. Assign the integration to a SwitchBot blind tilt device.
3. Observe (Image shows me changing configuration settings, see after 6 AM on purple line or the descent of the teal line around 12pm on the previous day)
![image](https://github.com/basbruss/adaptive-cover/assets/44243730/2103feff-19d8-4b23-9e37-f46137888d52)

### Debug logs

```text
N/A
```

**Comment by basbruss** [comment]
This is already possible with the `inverse state` option that changes the range from 0-100% to 100-0%

**Comment by AwesomenessZ** [comment]
This is correct. Sorry for some reason I was thinking the inverse was not what I wanted, but that I wanted just shifted up by 50%.

**Comment by Wildcat1** [comment]
@AwesomenessZ how do you assign the Tilted Blind integration to the Switchbot Blinds, can't see documentation on how to do that ? Thanks

**Comment by AwesomenessZ** [comment]
@Wildcat1 After you set up the integration, you should be able to configure -> fine tune settings -> assign a cover entity.


Admittedly, I don't do that and have an automation to interpret the output of this integration before applying it, since when I started using it there were not nearly as many features built in.

**Comment by Wildcat1** [comment]
@AwesomenessZ I got this assigned to the integration BUT even with configuring it, the shades never move. The adaptive cover logging shows the expected change BUT then says the shade is already at that level which its not. Any ideas ? Thanks

**Comment by AwesomenessZ** [comment]
@Wildcat1 Sorry I'm not sure, for me, they currently are always stuck at 56%, or 45% if I flip some of the switches around, so I haven't messed with it much recently.

For me, this started happening around the time the climate/weather stuff was added, so it might be a misconfiguration for me somewhere.

If it helps, I use this template based on the tilt cover position sensor:
```
data_template:
  tilt_position: "{{states.sensor.tilt_cover_position_living_room_blind_1.state | int + 5}}"
target:
  entity_id: cover.living_room_blinds_1
action: cover.set_cover_tilt_position
```
