### ISSUE TITLE
Updating a cover results in all entities becoming unavailable

### ISSUE THREAD

**Issue by FutureGUIs** [basbruss/adaptive-cover#70]
## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.34.0
Stage | running
Available Repositories | 1411
Downloaded Repositories | 68
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 468.7 GB
disk_used | 108.8 GB
healthy | true
supported | failed to load: Unsupported
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (3.4.1), MariaDB (2.6.1), Mosquitto broker (6.4.0), Nginx Proxy Manager (1.0.1), Overseerr (1.33.2), Portainer (2.19.4-3), Home Assistant Google Drive Backup (0.112.1), MQTT Explorer (browser-1.0.1), Radarr (5.3.6.8612), Sonarr (4.0.2.1262), Network UPS Tools (0.13.0), ESPHome (2024.2.2), Prowlarr NAS (nightly-1.14.2.4318-ls127), Zigbee2MQTT (1.36.0-1), Matter Server (5.4.1), Silicon Labs Multiprotocol (2.4.4), Scrypted (18-jammy-full.s6-v0.93.0), AdGuard Home (5.0.4), Mylar3 (0.7.8), Readarr (0.3.20.2452), Calibre (7.6.0), Studio Code Server (5.15.0), InfluxDB (5.0.0), Grafana (9.2.0), qBittorrent (4.6.3-4), rtlamr2mqtt (2.3.4), Piper (1.5.0), WeatherFlow to MQTT (3.2.2)

</details>

<details><summary>Husqvarna Automower</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 37
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 13, 2024 at 10:41 PM
-- | --
current_recorder_run | March 13, 2024 at 10:56 AM
estimated_db_size | 4616.44 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After changing some properties during a 'reconfigure' and saving, all the entities end up becoming unavailable.  

### Reproduction steps

1. Change some configuration on an existing cover 
2. Hit save
3. all devices show unavailable
...

### Diagnostics dump

Logger: homeassistant.config_entries
Source: config_entries.py:672
First occurred: 2:10:36 PM (1 occurrences)
Last logged: 2:10:36 PM

Error unloading entry Tilt Great Room Blinds for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 672, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 105, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by FutureGUIs** [comment]
Sorry I keep finding these, I do love what you're doing though :)

**Comment by basbruss** [comment]
Need to investigate that more. Does a restart work? I can remember that the sensors came back alive after a restart in my dev-env.

**Comment by FutureGUIs** [comment]
hmm, I'll have to try

**Comment by basbruss** [comment]
I guess I've found a fix. Will be releasing it soon, just needs some more testing
