### ISSUE TITLE
Error message calculation some Azimuths?

### ISSUE THREAD

**Issue by gitbock** [basbruss/adaptive-cover#8]
## System Information

version | core-2023.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4890
Installed Version | 1.33.0
Stage | running
Available Repositories | 1322
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.1
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 30.8 GB
disk_used | 15.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.13.0), Advanced SSH & Web Terminal (15.1.0), Node-RED (15.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 22, 2023 at 16:25
-- | --
current_recorder_run | November 1, 2023 at 21:00
estimated_db_size | 5249.68 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi,
and thanks for this great work ❤️ 

I created 4 sensors for horizontal blinds.
- north
- east
- south
- west

For each I calculated the azimuth by using the compass from open streetmap. However, I realized that for the north-facing side (Azimuth 15)  and west-facing side (Azimuth 298) I do not receive values and the log shows errors. East and south working fine.

<details>
  <summary>Screenshots</summary>

![2023-11-01 12_46_48-Settings – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/12010962/fbbbed4d-be30-48d1-afda-53b68861d5ae)
![2023-11-01 12_47_09-Dashboards – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/12010962/391d7673-a6b1-4f55-88c8-71ae6777ea78)
![2023-11-01 12_47_59-OpenStreetMap Compass _ Plot and Record OpenStreetMap Routes](https://github.com/basbruss/adaptive-cover/assets/12010962/83a8b397-1f75-4c32-b68d-5558e253a734)
![2023-11-01 21_15_54-Developer tools – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/12010962/f8e438ba-abf1-42d2-bbc2-b86c871de69b)
  
</details>

Anything I am doing wrong? 🤔 

Thank you!

### Reproduction steps

1. create new sensor, horizontal blinds, Azimuth 15
2. restart HA
3. watch the state: it shows unavailable

### Debug logs

```text
Log File:
**********

2023-11-01 21:00:27.957 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up adaptive_cover platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1022, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/adaptive_cover/sensor.py", line 101, in async_added_to_hass
self.async_update_state()
File "/config/custom_components/adaptive_cover/sensor.py", line 106, in async_update_state
self._cover_data.update()
File "/config/custom_components/adaptive_cover/sensor.py", line 221, in update
self.start = params.solar_times()[0]
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/adaptive_cover/calculation.py", line 65, in solar_times
return solpos[frame].index[0].to_pydatetime(), solpos[frame].index[-1].to_pydatetime()
~~~~~~~~~~~~~~~~~~~^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5365, in __getitem__
return getitem(key)
^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/arrays/datetimelike.py", line 376, in __getitem__
result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/arrays/_mixins.py", line 276, in __getitem__
result = self._ndarray[key]
~~~~~~~~~~~~~^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by basbruss** [comment]
Thanks for the detailed issue log!

I will release a fix shortly.

Although a sensor for North/North-West could be not that useful in the Northern Hemisphere as most of the time the sun is already below the horizon, so the calculations are not performed.
