### ISSUE TITLE
Switch for turning on/off automatic control

### ISSUE THREAD

**Issue by tschoiss** [basbruss/adaptive-cover#90]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Sometimes I need another position then the integration calculates. For example when watching a moving during day I want to close the shutter.

### Describe the solution you'd like

A switch which turns on/off the automatic control via the integration.

### Describe alternatives you've considered

Similar to the adaptive lightning integration, a check if the position has changed via a manual input. 

### Additional context

.

**Comment by basbruss** [comment]
Do you mean a switch that enables to listen for manual overrides? Or a switch to disable adaptive adjusting of the position. The later is already included and the first one is planned, but needs to get form yet.

**Comment by tschoiss** [comment]
Yes, I meant more or less both. Thanks for the information that this is planned.
