### ISSUE TITLE
Switch to change between Basic and Climate mode

### ISSUE THREAD

**Issue by tschoiss** [basbruss/adaptive-cover#91]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Right now, the inside temperature is than the maximum comfort temperature. But it is so sunny, that I want the shutter to be controlled as the temperature between the thresholds and not closed completely. 

### Describe the solution you'd like

A switch which changes the between basic and climate mode

### Describe alternatives you've considered

A option to turn off/on the completely closing behaviour.

### Additional context

.

**Comment by basbruss** [comment]
But the things you describe are already present.
<img width="348" alt="Screen Shot 2024-04-04 at 13 17 25" src="https://github.com/basbruss/adaptive-cover/assets/68892092/c5ec934f-18b5-4f2f-b3d8-9ffcda81c23e">
