### ISSUE TITLE
Add support for extra conditions from blueprint to internal automation as of 1.0.1

### ISSUE THREAD

**Issue by kodymallory** [basbruss/adaptive-cover#95]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

With the blueprint that it was using from automation, you could add "Additional Conditions" to the automation to prevent it from running. This was useful for configuring things like overrides if the cover was controlled by an entity other than the automation.

### Describe the solution you'd like

Migrate the functionality from the blueprint into the internal integration for Additional Conditions

### Describe alternatives you've considered

NA

### Additional context

![image](https://github.com/basbruss/adaptive-cover/assets/4483479/814f095d-15dc-4555-a29e-62ce2f9f07cb)

**Comment by basbruss** [comment]
You can use the `toggle control switch` in an automation to add extra conditions to it 😉 

EDIT: Or still use the blueprint and set that switch to off

**Comment by kodymallory** [comment]
Ah! That is a much cleaner and direct way of doing it. Thanks for the clarification
