### ISSUE TITLE
When comfort temperatures are reached I would like to have blocked everything with presence

### ISSUE THREAD

**Issue by miezie** [basbruss/adaptive-cover#96]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

For some screens/shutters I’d like to override the default presence behavior to provide daylight when at home to just close entirely by default when it is warm enough in the room. I think it would be cool to have this as a climate option. Eg. My screens provide enough daylight when at home on a sunny day in a hot room. And my blinds in the bedrooms could be closed anyway :)… I like it cold there.

### Describe the solution you'd like

Switch for override to have it on in summer and off in winter.

### Describe alternatives you've considered

I could fake it with presence or persons or settings… but I think it is wise climate behavior and a conscious choice for the screens/blinds.

### Additional context

It is wise to keep it as cold as possible to serve the climate on warm days. To prevent the need for other cooling solutions (cooling heat pumps, airco, etc.)

**Comment by basbruss** [comment]
> And my blinds in the bedrooms could be closed anyway :)… I like it cold there.

This is easily achieved by room presence or a mock input_boolean that has the state `off` when the bedrooms are on the right temperature.

It's not baked in the presence-climate logic, because the main goal is to prevent glare while providing as much as possible natural daylight. Indirect light doesn't heat a room as much up as direct daylight/radiation does.
